package hu.bme.aut.android.together.features.event.fragment.communication

import android.annotation.SuppressLint
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.navigation.fragment.findNavController
import androidx.navigation.fragment.navArgs
import com.google.android.material.badge.BadgeDrawable
import com.google.android.material.badge.BadgeUtils
import com.google.android.material.tabs.TabLayoutMediator
import hu.bme.aut.android.together.R
import hu.bme.aut.android.together.databinding.FragmentEventDetailsCommunicationBinding
import hu.bme.aut.android.together.features.event.adapter.CommunicationPanelsAdapter

/**
 * This fragment provides an user interface, which can be used to connect with the event's other
 * participants. Organisers can post news, and answer questions about the event. Participants
 * can ask questions about this event, and read the organisers' news posts.
 */
class EventDetailsCommunicationFragment : Fragment() {

    private val args: EventDetailsCommunicationFragmentArgs by navArgs()

    private lateinit var binding: FragmentEventDetailsCommunicationBinding

    private lateinit var pagerAdapter: CommunicationPanelsAdapter

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        binding = FragmentEventDetailsCommunicationBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        setUpToolbar()
        setUpTabBehaviour()
    }

    private fun setUpToolbar() {
        setUpOrganisersToolbarMenu()
        setNavigationActionBehaviour()
    }

    /**
     * If the user has organiser privilege, it can access an organiser specific menu on the toolbar;
     * this function sets this behaviour.
     */
    private fun setUpOrganisersToolbarMenu() {
        if (args.isOrganiser)
            addOrganiserActionsToToolbar()
    }

    /**
     * The organisers can use an inbox to check and answer incoming questions. This function sets
     * up this menu on the toolbar, and its inbox action's onclick behaviour.
     */
    // The function that uses this feature is already marked with this annotation, and it should be enough
    @SuppressLint("UnsafeExperimentalUsageError")
    private fun addOrganiserActionsToToolbar() {
        with(binding.tbEventDetailsCommunication) {
            inflateMenu(R.menu.organiser_incoming_questions_menu)
            setOnMenuItemClickListener {
                when (it.itemId) {
                    R.id.actionOrganiserEventQuestions -> {
                        EventDetailsCommunicationFragmentDirections.actionEventDetailsCommunicationFragmentToEventQuestionsFragment()
                            .let { action ->
                                findNavController().navigate(action)
                            }
                        true
                    }
                    else -> super.onOptionsItemSelected(it)
                }
            }
        }
        addQuestionCountBadge()
    }

    /**
     * Attaches badge to the organiser specific menu's inbox action. The badge represents the
     * count of incoming unanswered questions.
     */
    @com.google.android.material.badge.ExperimentalBadgeUtils
    private fun addQuestionCountBadge() {
        BadgeDrawable.create(requireContext()).apply {
            isVisible = true
            //TODO actual data should be used later
            number = 1
        }.let { badge ->
            BadgeUtils.attachBadgeDrawable(
                badge,
                binding.tbEventDetailsCommunication,
                R.id.actionOrganiserEventQuestions
            )
        }
    }

    /**
     * Sets the toolbar navigation icon's onclick behaviour. After the icon was clicked,
     * the BackStack is popped.
     */
    private fun setNavigationActionBehaviour() {
        binding.tbEventDetailsCommunication.setNavigationOnClickListener {
            findNavController().popBackStack()
        }
    }

    private fun setUpTabBehaviour() {
        initializeAndSetPagerAdapter()
        attachTabLayoutMediator()
    }

    private fun initializeAndSetPagerAdapter() {
        pagerAdapter = CommunicationPanelsAdapter(this, args.isOrganiser)
        binding.vp2CommunicationPanels.adapter = pagerAdapter
    }

    /**
     * Attaches a TabLayoutMediator to the contained ViePager2 and TabLayout widget.
     * The tab's name are generated by calling [pagerAdapter]'s [CommunicationPanelsAdapter.getTabName]
     * function.
     */
    private fun attachTabLayoutMediator() {
        TabLayoutMediator(
            binding.tlCommunicationPanels,
            binding.vp2CommunicationPanels
        ) { tab, position ->
            tab.text = pagerAdapter.getTabName(position)
        }.attach()
    }
}