language: android
dist: trusty
jdk: oraclejdk8
sudo: required
env:
  global:
    - MALLOC_ARENA_MAX=2
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
android: 
  components:
    - add-on
    - extra 
    - platform-tools 
    - tools 
    - extra-google-googleplayservices
    - extra-google-m2repository 
    - extra-android-m2repository 
    - addon-google_apis-google-28 
    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
before_script:
 - chmod +x gradlew
 - echo no | android create avd --force -n test -t android-28 --abi armeabi-v7a -s "768x1280"
 - emulator -avd test -no-audio -no-window &
 - adb wait-for-device
 - adb shell input keyevent 82 &
script: ./gradlew :app:build :app:connectedDebugAndroidTest